### ISSUE TITLE
Task List qzcad

### ISSUE THREAD

**Issue by qzcad** [qzcad/qzcad-tree#1]
- [ ] mainwindow.cpp: добавить универсальный метод для визуализации метрики сетки (на элементе);
- [ ] glmeshpicture.cpp: перенести вывод вспомогательной информации в paintEvent(QPaintEvent \* event)

---

Добавить диалоги управления режимами визуализации:
- [ ] диалог выбора цвета сетки
- [ ] диалог выбора цвета элемента
- [ ] диалог выбора цвета фона
- [ ] диалог выбора количества цветов, используемых при визуализации значений на дискретной модели

---
- [ ] Диалог настроек редактора модели

---
- [ ] Сохранение настроек пользователя, используя QSettings
