### ISSUE TITLE
Task List mesh

### ISSUE THREAD

**Issue by qzcad** [qzcad/qzcad-tree#2]
Класс TriangleMesh3D:
- [ ] Добавить поиск особых точек на границе цилиндрической области при функциональном представлении отверстий
- [ ] Добавить реализацию построения триангуляции конической области при функциональном представлении отверстий
- [ ] Добавить реализацию построения триангуляции поверхности Безье при функциональном представлении отверстий
- [ ] Добавить реализацию построения триангуляции поверхности NURBS при функциональном представлении отверстий
- [ ] Добавить взвешенное сглаживание Лапласа, основанное на дистанциях между узлами в 3D
- [ ] Добавить метод для сглаживания на основе максимизации суммы квадратов минимальных углов треугольников (оптимизация производится в местной системе координат, угол вычисляется в глобальной системе)

По всем классам генерации сетки:
- [ ] Восстановить соответствие типов точек ожидаемым
