### ISSUE TITLE
Task List qzfem

### ISSUE THREAD

**Issue by qzcad** [qzcad/qzcad-tree#3]
- [ ] Для расчета многослойных пластин использовать пять степеней свободы (теория сдвиговых деформаций первого порядка
- [ ] Перевести на функциональную модель описания параметров МКЭ трехмерный расчет
- [ ] Добавить возможность определения направления действия граничного условия или силы через побитовые логические операции
